[package]
name = "blinking-led"
version = "0.1.0"
authors = ["punctuationmarks <punctuationmarks@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_gpiozero = "0.2.0"
